// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGltgDrKkG1oAZwPQjEUbvM02Ukvk264',
    appId: '1:856199784183:web:a02ced96d2889d7f23d5f2',
    messagingSenderId: '856199784183',
    projectId: 'deenfit',
    authDomain: 'deenfit.firebaseapp.com',
    storageBucket: 'deenfit.firebasestorage.app',
    measurementId: 'G-FJ2MJZRMNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVf3PIGsy_171ImsfvUR-pWDNVg7OrrbE',
    appId: '1:856199784183:android:b596ca66635e759b23d5f2',
    messagingSenderId: '856199784183',
    projectId: 'deenfit',
    storageBucket: 'deenfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUNqmgfPuvSAmdBG3XPYnkedyL26ueAY',
    appId: '1:856199784183:ios:96ea2361bafd165d23d5f2',
    messagingSenderId: '856199784183',
    projectId: 'deenfit',
    storageBucket: 'deenfit.firebasestorage.app',
    iosBundleId: 'com.example.deenfitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBUNqmgfPuvSAmdBG3XPYnkedyL26ueAY',
    appId: '1:856199784183:ios:e06677d6e7de08a723d5f2',
    messagingSenderId: '856199784183',
    projectId: 'deenfit',
    storageBucket: 'deenfit.firebasestorage.app',
    iosBundleId: 'com.app.deenfitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxGltgDrKkG1oAZwPQjEUbvM02Ukvk264',
    appId: '1:856199784183:web:d3b2bc6f413ab2f023d5f2',
    messagingSenderId: '856199784183',
    projectId: 'deenfit',
    authDomain: 'deenfit.firebaseapp.com',
    storageBucket: 'deenfit.firebasestorage.app',
    measurementId: 'G-B9XMHW071N',
  );
}
